name: proto

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  run:
    name: Proto
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "proto"
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,subdir=proto"
