name: sqlc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '0 10 * * 1' # run "At 10:00 on Monday"
  workflow_call:

jobs:
  run:
    name: Sqlc
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - name: Install SQLc
        uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.21.0'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run sqlc diff
        run: cd internal/sqlbackend/ && sqlc diff

      - name: Run sqlc vet
        run: cd internal/sqlbackend/ && sqlc vet
